package com.junwen.videoplayer.DB.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.junwen.videoplayer.DB.entity.NetWorkEntity;
import com.junwen.videoplayer.DB.entity.VideoServerEntity;

import com.junwen.videoplayer.DB.dao.NetWorkDao;
import com.junwen.videoplayer.DB.dao.VideoServerEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig netWorkDaoConfig;
    private final DaoConfig videoServerEntityDaoConfig;

    private final NetWorkDao netWorkDao;
    private final VideoServerEntityDao videoServerEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        netWorkDaoConfig = daoConfigMap.get(NetWorkDao.class).clone();
        netWorkDaoConfig.initIdentityScope(type);

        videoServerEntityDaoConfig = daoConfigMap.get(VideoServerEntityDao.class).clone();
        videoServerEntityDaoConfig.initIdentityScope(type);

        netWorkDao = new NetWorkDao(netWorkDaoConfig, this);
        videoServerEntityDao = new VideoServerEntityDao(videoServerEntityDaoConfig, this);

        registerDao(NetWorkEntity.class, netWorkDao);
        registerDao(VideoServerEntity.class, videoServerEntityDao);
    }
    
    public void clear() {
        netWorkDaoConfig.getIdentityScope().clear();
        videoServerEntityDaoConfig.getIdentityScope().clear();
    }

    public NetWorkDao getNetWorkDao() {
        return netWorkDao;
    }

    public VideoServerEntityDao getVideoServerEntityDao() {
        return videoServerEntityDao;
    }

}
