package com.junwen.videoplayer.DB.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import cn.bmob.v3.BmobObject;

/**
 * Entity mapped to table NetWorkInfo.
 */
public class NetWorkEntity extends BmobObject{

    private Long vid;
    private String videoName;
    private String videoUrl;
    private String videoType;
    private String thumbnail;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public NetWorkEntity() {
    }

    public NetWorkEntity(Long vid) {
        this.vid = vid;
    }

    public NetWorkEntity(Long vid, String videoName, String videoUrl, String videoType, String thumbnail) {
        this.vid = vid;
        this.videoName = videoName;
        this.videoUrl = videoUrl;
        this.videoType = videoType;
        this.thumbnail = thumbnail;
    }

    public Long getVid() {
        return vid;
    }

    public void setVid(Long vid) {
        this.vid = vid;
    }

    public String getVideoName() {
        return videoName;
    }

    public void setVideoName(String videoName) {
        this.videoName = videoName;
    }

    public String getVideoUrl() {
        return videoUrl;
    }

    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl;
    }

    public String getVideoType() {
        return videoType;
    }

    public void setVideoType(String videoType) {
        this.videoType = videoType;
    }

    public String getThumbnail() {
        return thumbnail;
    }

    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
