package com.junwen.videoplayer.DB.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import java.io.Serializable;

/**
 * Entity mapped to table VideoServerEntityInfo.
 */
public class VideoServerEntity implements Serializable{

    private Long vid;
    private String videoName;
    private String videoUrl;
    private String thumbnail;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public VideoServerEntity() {
    }

    public VideoServerEntity(Long vid) {
        this.vid = vid;
    }

    public VideoServerEntity(Long vid, String videoName, String videoUrl, String thumbnail) {
        this.vid = vid;
        this.videoName = videoName;
        this.videoUrl = videoUrl;
        this.thumbnail = thumbnail;
    }

    public Long getVid() {
        return vid;
    }

    public void setVid(Long vid) {
        this.vid = vid;
    }

    public String getVideoName() {
        return videoName;
    }

    public void setVideoName(String videoName) {
        this.videoName = videoName;
    }

    public String getVideoUrl() {
        return videoUrl;
    }

    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl;
    }

    public String getThumbnail() {
        return thumbnail;
    }

    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
